#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.Sys
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Sys\Error.cshtml"
    using Singular.Modules.Core.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Sys/Error.cshtml")]
    public partial class Error : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Error()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Sys\Error.cshtml"
  
    ViewBag.Title = Html.Translate("Error");
    ViewBag.NoNg = true;

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>");

            
            #line 7 "..\..\Views\Sys\Error.cshtml"
Write(Html.Translate("Er... really sorry.... an error has occured"));

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n<p>");

            
            #line 8 "..\..\Views\Sys\Error.cshtml"
Write(Html.Translate("Please try again. Or just give up."));

            
            #line default
            #line hidden
WriteLiteral("</p>");

        }
    }
}
#pragma warning restore 1591
