#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.Sys
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Sys\PageNotFound.cshtml"
    using Singular.Modules.Core.HtmlExtensions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Sys\PageNotFound.cshtml"
    using Singular.Web.Mvc.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Sys/PageNotFound.cshtml")]
    public partial class PageNotFound : System.Web.Mvc.WebViewPage<dynamic>
    {
        public PageNotFound()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Sys\PageNotFound.cshtml"
  
    ViewBag.Title = Html.Translate("Page Not Found");
    ViewBag.NgAppName = "Singular.Modules.SingularSysApp";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 277), Tuple.Create("\"", 390)
            
            #line 10 "..\..\Views\Sys\PageNotFound.cshtml"
, Tuple.Create(Tuple.Create("", 283), Tuple.Create<System.Object, System.Int32>(Url.EmbeddedContent("Core", "~/Content/Ng/Modules/SingularSysApp.js", IncludeBehaviour.MinifyWhenNotDebug)
            
            #line default
            #line hidden
, 283), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("<h2>");

            
            #line 12 "..\..\Views\Sys\PageNotFound.cshtml"
Write(Html.Translate("Ooops... we couldn't find that page!"));

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n<p>");

            
            #line 13 "..\..\Views\Sys\PageNotFound.cshtml"
Write(Html.Translate("Please try again. Or just give up."));

            
            #line default
            #line hidden
WriteLiteral("</p>");

        }
    }
}
#pragma warning restore 1591
