#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_CoreBrand.cshtml"
    using Singular.Modules.Core.HtmlExtensions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\_CoreBrand.cshtml"
    using Singular.Web.Mvc.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_CoreBrand.cshtml")]
    public partial class CoreBrand : System.Web.Mvc.WebViewPage<Singular.Modules.Core.ViewModels.CoreViewModelBase>
    {
        public CoreBrand()
        {
        }
        public override void Execute()
        {
WriteLiteral("<a");

WriteAttribute("style", Tuple.Create(" style=\"", 179), Tuple.Create("\"", 270)
, Tuple.Create(Tuple.Create("", 187), Tuple.Create("background-image:", 187), true)
, Tuple.Create(Tuple.Create(" ", 204), Tuple.Create("url(\'", 205), true)
            
            #line 5 "..\..\Views\Shared\_CoreBrand.cshtml"
, Tuple.Create(Tuple.Create("", 210), Tuple.Create<System.Object, System.Int32>(Url.EmbeddedContent("Core", "~/Content/Images/Logo.png")
            
            #line default
            #line hidden
, 210), false)
, Tuple.Create(Tuple.Create("", 267), Tuple.Create("\');", 267), true)
);

WriteLiteral("\r\n   class=\"navbar-brand\"");

WriteAttribute("href", Tuple.Create("\r\n   href=\"", 296), Tuple.Create("\"", 335)
            
            #line 7 "..\..\Views\Shared\_CoreBrand.cshtml"
, Tuple.Create(Tuple.Create("", 307), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 307), false)
);

WriteLiteral("\r\n   data-ng-click=\"Ui.ShowLoader()\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Shared\_CoreBrand.cshtml"
                     Write(Html.Translate(Model.SiteContext.SiteName));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    <span");

WriteLiteral(" class=\"hidden\"");

WriteLiteral(">S</span>ingular\r\n</a>");

        }
    }
}
#pragma warning restore 1591
