#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_Loader.cshtml"
    using Singular.Web.Mvc.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Loader.cshtml")]
    public partial class Loader : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Loader()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"sg-loader\"");

WriteLiteral(" data-ng-class=\"{\'in\':Ui.LoaderVisible==true}\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"sg-loader-overlay\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"sg-loader-inner\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"sg-loader-inner-inner\"");

WriteAttribute("style", Tuple.Create(" style=\"", 269), Tuple.Create("\"", 361)
, Tuple.Create(Tuple.Create("", 277), Tuple.Create("background-image:", 277), true)
, Tuple.Create(Tuple.Create(" ", 294), Tuple.Create("url(\'", 295), true)
            
            #line 6 "..\..\Views\Shared\_Loader.cshtml"
, Tuple.Create(Tuple.Create("", 300), Tuple.Create<System.Object, System.Int32>(Url.EmbeddedContent("Core","~/Content/Images/Shape51.png")
            
            #line default
            #line hidden
, 300), false)
, Tuple.Create(Tuple.Create("", 359), Tuple.Create("\')", 359), true)
);

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
