#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Views\Shared\_Nav.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\_Nav.cshtml"
    using Singular.Web.Mvc.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Nav.cshtml")]
    public partial class Nav : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Nav()
        {
        }
        public override void Execute()
        {
WriteLiteral("<nav");

WriteLiteral(" class=\"navbar navbar-default\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <!-- Brand and toggle get grouped for better mobile display -->\r\n     " +
"   <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral("\r\n                    class=\"navbar-toggle\"");

WriteLiteral("\r\n                    data-toggle=\"collapse\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            </button>\r\n            <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteAttribute("href", Tuple.Create(" href=\"", 695), Tuple.Create("\"", 729)
            
            #line 16 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 702), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 702), false)
);

WriteLiteral(">Singular Framework</a>\r\n        </div>\r\n\r\n        <!-- Collect the nav links, fo" +
"rms, and other content for toggling -->\r\n        <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 963), Tuple.Create("\"", 1001)
            
            #line 22 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 970), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Singular/Core")
            
            #line default
            #line hidden
, 970), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1002), Tuple.Create("\"", 1033)
            
            #line 22 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 1010), Tuple.Create<System.Object, System.Int32>(Html.Translate("Home")
            
            #line default
            #line hidden
, 1010), false)
);

WriteLiteral(">");

            
            #line 22 "..\..\Views\Shared\_Nav.cshtml"
                                                                                         Write(Html.Translate("Home"));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a");

WriteLiteral(" href=\"#\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1100), Tuple.Create("\"", 1137)
            
            #line 23 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 1108), Tuple.Create<System.Object, System.Int32>(Html.Translate("My account")
            
            #line default
            #line hidden
, 1108), false)
);

WriteLiteral(">");

            
            #line 23 "..\..\Views\Shared\_Nav.cshtml"
                                                                 Write(Html.Translate("My account"));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Random button <span");

WriteLiteral(" class=\"glyphicon glyphicon-calendar\"");

WriteLiteral("></span></a></li>\r\n            </ul>\r\n        </div><!-- /.navbar-collapse -->\r\n " +
"   </div><!-- /.container-fluid -->\r\n</nav>\r\n");

        }
    }
}
#pragma warning restore 1591
