#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Views\Shared\_Nav.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\_Nav.cshtml"
    using Singular.Web.Mvc.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Nav.cshtml")]
    public partial class Nav : System.Web.Mvc.WebViewPage<Singular.Modules.Core.ViewModels.CoreViewModelBase>
    {
        public Nav()
        {
        }
        public override void Execute()
        {
WriteLiteral("<nav");

WriteLiteral(" class=\"navbar navbar-default\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <!-- Brand and toggle get grouped for better mobile display -->\r\n     " +
"   <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral("\r\n                    class=\"navbar-toggle\"");

WriteLiteral("\r\n                    data-toggle=\"collapse\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            </button>\r\n            <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteAttribute("href", Tuple.Create(" href=\"", 747), Tuple.Create("\"", 781)
            
            #line 16 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 754), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 754), false)
);

WriteLiteral(">");

            
            #line 16 "..\..\Views\Shared\_Nav.cshtml"
                                                                  Write(Html.Translate("Singular Framework"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        </div>\r\n\r\n        <!-- Collect the nav links, forms, and other cont" +
"ent for toggling -->\r\n        <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\Shared\_Nav.cshtml"
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\_Nav.cshtml"
                 foreach (var section in Model.Sections)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1112), Tuple.Create("\"", 1162)
            
            #line 24 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 1120), Tuple.Create<System.Object, System.Int32>(section.IsActive.Invoke() ? "active":""
            
            #line default
            #line hidden
, 1120), false)
);

WriteLiteral(">\r\n                        <a");

WriteAttribute("title", Tuple.Create(" title=\"", 1192), Tuple.Create("\"", 1272)
            
            #line 25 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 1200), Tuple.Create<System.Object, System.Int32>(Html.Translate(section.Name)
            
            #line default
            #line hidden
, 1200), false)
, Tuple.Create(Tuple.Create(" ", 1231), Tuple.Create("|", 1232), true)
            
            #line 25 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create(" ", 1233), Tuple.Create<System.Object, System.Int32>(Html.Translate(section.Description)
            
            #line default
            #line hidden
, 1234), false)
);

WriteAttribute("href", Tuple.Create("\r\n                           href=\"", 1273), Tuple.Create("\"", 1376)
            
            #line 26 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 1308), Tuple.Create<System.Object, System.Int32>(Url.Action(section.Action, section.Controller, section.RouteValues)
            
            #line default
            #line hidden
, 1308), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 27 "..\..\Views\Shared\_Nav.cshtml"
                        Write(Html.Translate(section.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </li>\r\n");

            
            #line 30 "..\..\Views\Shared\_Nav.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </div><!-- /.navbar-collapse -->\r\n    </div><!-- /.con" +
"tainer-fluid -->\r\n</nav>\r\n");

        }
    }
}
#pragma warning restore 1591
