#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Views\Shared\_Nav.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\_Nav.cshtml"
    using Singular.Modules.Core.HtmlExtensions;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_Nav.cshtml"
    using Singular.Web.Mvc.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Nav.cshtml")]
    public partial class Nav : System.Web.Mvc.WebViewPage<Singular.Modules.Core.ViewModels.CoreViewModelBase>
    {
        public Nav()
        {
        }
        public override void Execute()
        {
WriteLiteral("<nav");

WriteLiteral(" class=\"navbar navbar-default navbar-fixed-top\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <!-- Brand and toggle get grouped for better mobile display -->\r\n     " +
"   <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral("\r\n                    class=\"navbar-toggle\"");

WriteLiteral("\r\n                    data-toggle=\"collapse\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            </button>\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Views\Shared\_Nav.cshtml"
       Write(Html.Partial(Model.SiteContext.BrandViewPath));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <!-- Collect the nav links, forms, and other content " +
"for toggling -->\r\n        <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav navbar-nav mb-only\"");

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Views\Shared\_Nav.cshtml"
                
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\_Nav.cshtml"
                 foreach (var section in Model.Sections)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1128), Tuple.Create("\"", 1180)
            
            #line 25 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 1136), Tuple.Create<System.Object, System.Int32>(section.IsActive.Invoke() ? "active" : ""
            
            #line default
            #line hidden
, 1136), false)
);

WriteLiteral(">\r\n                        <a");

WriteLiteral(" data-ng-click=\"Ui.ShowLoader()\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1242), Tuple.Create("\"", 1340)
, Tuple.Create(Tuple.Create("", 1250), Tuple.Create("background-image:", 1250), true)
, Tuple.Create(Tuple.Create(" ", 1267), Tuple.Create("url(\'", 1268), true)
            
            #line 26 "..\..\Views\Shared\_Nav.cshtml"
         , Tuple.Create(Tuple.Create("", 1273), Tuple.Create<System.Object, System.Int32>(Url.EmbeddedContent(section.AreaName, section.ImageVirtualPath)
            
            #line default
            #line hidden
, 1273), false)
, Tuple.Create(Tuple.Create("", 1337), Tuple.Create("\');", 1337), true)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1341), Tuple.Create("\"", 1421)
            
            #line 26 "..\..\Views\Shared\_Nav.cshtml"
                                                                                      , Tuple.Create(Tuple.Create("", 1349), Tuple.Create<System.Object, System.Int32>(Html.Translate(section.Name)
            
            #line default
            #line hidden
, 1349), false)
, Tuple.Create(Tuple.Create(" ", 1380), Tuple.Create("|", 1381), true)
            
            #line 26 "..\..\Views\Shared\_Nav.cshtml"
                                                                                                                       , Tuple.Create(Tuple.Create(" ", 1382), Tuple.Create<System.Object, System.Int32>(Html.Translate(section.Description)
            
            #line default
            #line hidden
, 1383), false)
);

WriteAttribute("href", Tuple.Create("\r\n                           href=\"", 1422), Tuple.Create("\"", 1525)
            
            #line 27 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 1457), Tuple.Create<System.Object, System.Int32>(Url.Action(section.Action, section.Controller, section.RouteValues)
            
            #line default
            #line hidden
, 1457), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 28 "..\..\Views\Shared\_Nav.cshtml"
                        Write(Html.Translate(section.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </li>\r\n");

            
            #line 31 "..\..\Views\Shared\_Nav.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n");

            
            #line 33 "..\..\Views\Shared\_Nav.cshtml"
            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Shared\_Nav.cshtml"
             if (Model.SingularContext.IsAuthenticated)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"user-info\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"user-info-inner\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"user-info-logout\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" ng-click=\"Ui.ShowLoader()\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1962), Tuple.Create("\"", 1997)
            
            #line 38 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 1970), Tuple.Create<System.Object, System.Int32>(Html.Translate("Logout")
            
            #line default
            #line hidden
, 1970), false)
);

WriteAttribute("href", Tuple.Create("\r\n                               href=\"", 1998), Tuple.Create("\"", 2099)
            
            #line 39 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 2037), Tuple.Create<System.Object, System.Int32>(Url.Action( "Logout",new{area="Core",controller="FormsAuth"})
            
            #line default
            #line hidden
, 2037), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 40 "..\..\Views\Shared\_Nav.cshtml"
                            Write(Html.Translate("Logout"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </a>\r\n                        </div>\r\n             " +
"           <div");

WriteLiteral(" class=\"user-info-click\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" ng-click=\"Ui.ShowLoader()\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2342), Tuple.Create("\"", 2378)
            
            #line 44 "..\..\Views\Shared\_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 2349), Tuple.Create<System.Object, System.Int32>(Url.Action("MyInfo","Users")
            
            #line default
            #line hidden
, 2349), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 2379), Tuple.Create("\"", 2468)
, Tuple.Create(Tuple.Create("", 2387), Tuple.Create("background-image:", 2387), true)
, Tuple.Create(Tuple.Create(" ", 2404), Tuple.Create("url(\'", 2405), true)
            
            #line 44 "..\..\Views\Shared\_Nav.cshtml"
                                             , Tuple.Create(Tuple.Create("", 2410), Tuple.Create<System.Object, System.Int32>(Url.EmbeddedContent("Core","~/Content/Images/Man.png")
            
            #line default
            #line hidden
, 2410), false)
, Tuple.Create(Tuple.Create("", 2465), Tuple.Create("\');", 2465), true)
);

WriteAttribute("title", Tuple.Create(" title=\"", 2469), Tuple.Create("\"", 2512)
            
            #line 44 "..\..\Views\Shared\_Nav.cshtml"
                                                                                                                , Tuple.Create(Tuple.Create("", 2477), Tuple.Create<System.Object, System.Int32>(Html.Translate("Your information")
            
            #line default
            #line hidden
, 2477), false)
);

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 45 "..\..\Views\Shared\_Nav.cshtml"
                                                 Write(Html.Translate("Your information"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </a>\r\n                        </div>\r\n      " +
"              </div>\r\n                </div>\r\n");

            
            #line 50 "..\..\Views\Shared\_Nav.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div><!-- /.navbar-collapse -->\r\n    </div><!-- /.container-fluid -->\r\n<" +
"/nav>");

        }
    }
}
#pragma warning restore 1591
