#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Home\Index.cshtml"
    using Singular.Modules.Core.HtmlExtensions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Home\Index.cshtml"
    using Singular.Web.Mvc.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = Html.Translate("The Stuff Management system");
    ViewBag.NgAppName = "Singular.Modules.SingularCoreApp";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 291), Tuple.Create("\"", 404)
            
            #line 10 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 297), Tuple.Create<System.Object, System.Int32>(Url.EmbeddedContent("Core","~/Content/Ng/Modules/SingularCoreApp.js", IncludeBehaviour.MinifyWhenNotDebug)
            
            #line default
            #line hidden
, 297), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n<h2>Welcome to the Singular Framework</h2>\r\n<p>Viral chillwave keytar, next lev" +
"el Godard master cleanse Pinterest meh aesthetic Pitchfork umami locavore.</p>\r\n" +
"<div");

WriteLiteral(" class=\"jumbotron text-center\"");

WriteLiteral(">\r\n    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 626), Tuple.Create("\"", 688)
            
            #line 16 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 632), Tuple.Create<System.Object, System.Int32>(Url.EmbeddedContent("Core","~/Content/Images/Logo.png")
            
            #line default
            #line hidden
, 632), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 689), Tuple.Create("\"", 732)
            
            #line 16 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 695), Tuple.Create<System.Object, System.Int32>(Html.Translate("Singular Framework")
            
            #line default
            #line hidden
, 695), false)
);

WriteLiteral("/>\r\n</div>\r\n<p>Fixie bitters fanny pack, flannel 8-bit taxidermy +1 selfies Kicks" +
"tarter fashion axe mlkshk VHS salvia. IPhone Helvetica cray High Life.</p>\r\n");

        }
    }
}
#pragma warning restore 1591
