#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.FormsAuth
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\FormsAuth\Index.cshtml"
    using Singular.Modules.Core.HtmlExtensions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\FormsAuth\Index.cshtml"
    using Singular.Web.Mvc.Common.HtmlExtensions;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\FormsAuth\Index.cshtml"
    using Singular.Web.Mvc.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/FormsAuth/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Singular.Modules.Core.ViewModels.FormsAuthViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\FormsAuth\Index.cshtml"
  
    ViewBag.Title = Html.Translate("Login");
    ViewBag.NgAppName = "Singular.Modules.SingularFormsAuthApp";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 11 "..\..\Views\FormsAuth\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 405), Tuple.Create("\"", 524)
            
            #line 15 "..\..\Views\FormsAuth\Index.cshtml"
, Tuple.Create(Tuple.Create("", 411), Tuple.Create<System.Object, System.Int32>(Url.EmbeddedContent("Core", "~/Content/Ng/Modules/SingularFormsAuthApp.js", IncludeBehaviour.MinifyWhenNotDebug)
            
            #line default
            #line hidden
, 411), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("<div");

WriteLiteral(" ng-controller=\"FormsAuthController\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n");

            
            #line 19 "..\..\Views\FormsAuth\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\FormsAuth\Index.cshtml"
     using (Html.BeginNgForm(x => x
        .OnSubmit("Login()")
        .CssClass("sg-form")
        //.UseDataPrefix()
        ))
    {
        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\FormsAuth\Index.cshtml"
   Write(Html.NgEditorFor(x => x.Email, x => x
                .TextBox()
                .ModelPrefix("Model")
                .BootstrapFormControl()
                .BootstrapFormGroup()
                .LabelText(Html.Translate("Email"))
                .Attribute("type", "email")
                .Attribute("ng-required", "true")
                .Attribute("autocomplete","off")
            //.UseDataPrefix()
        ));

            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\FormsAuth\Index.cshtml"
         
        
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\FormsAuth\Index.cshtml"
   Write(Html.NgEditorFor(x => x.Password, x => x
                .TextBox()
                .BootstrapFormControl()
                .BootstrapFormGroup()
                .LabelText(Html.Translate("Password"))
                .Attribute("type", "password")
                .Attribute("ng-required", "true")
            //.UseDataPrefix()
        ));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\FormsAuth\Index.cshtml"
         
        using (Html.BeginBootstrapFormGroup())
        {
            
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\FormsAuth\Index.cshtml"
       Write(Html.BootstrapButton(x => x
                .BootstrapButton("primary")
                .BeforeGlyph("ok")
                .LabelText(Html.Translate("Submit"))
                .Attribute("type", "submit")
                .Attribute("ng-disabled", "!FormIsValid()")
                .CssClass("margin-right-half")
                //.UseDataPrefix()
            ));

            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\FormsAuth\Index.cshtml"
             

            
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\FormsAuth\Index.cshtml"
       Write(Html.BootstrapButton(x => x
                .BootstrapButton("danger")
                .AfterGlyph("remove")
                .LabelText(Html.Translate("Reset"))
                .Attribute("type", "reset")
                //.UseDataPrefix()
            ));

            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\FormsAuth\Index.cshtml"
             
        }

    }

            
            #line default
            #line hidden
WriteLiteral("    \r\n    <div>Email: {{ stng.IsNullOrEmpty(Model.Email) ? \"UNDEFINED\":Model.Emai" +
"l }}</div>\r\n    <div>Password: {{ stng.IsNullOrEmpty(Model.Password) ? \"UNDEFINE" +
"D\":Model.Password }}</div>\r\n\r\n\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
