#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.FormsAuth
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\Views\FormsAuth\Index.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\FormsAuth\Index.cshtml"
    using Singular.Modules.Core.HtmlExtensions;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\FormsAuth\Index.cshtml"
    using Singular.Web.Mvc.Common.HtmlExtensions;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\FormsAuth\Index.cshtml"
    using Singular.Web.Mvc.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/FormsAuth/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Singular.Modules.Core.ViewModels.FormsAuthViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\Views\FormsAuth\Index.cshtml"
  
    ViewBag.Title = Html.Translate("Login");
    ViewBag.NgAppName = "Singular.Modules.SingularFormsAuthApp";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 12 "..\..\Views\FormsAuth\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 428), Tuple.Create("\"", 547)
            
            #line 16 "..\..\Views\FormsAuth\Index.cshtml"
, Tuple.Create(Tuple.Create("", 434), Tuple.Create<System.Object, System.Int32>(Url.EmbeddedContent("Core", "~/Content/Ng/Modules/SingularFormsAuthApp.js", IncludeBehaviour.MinifyWhenNotDebug)
            
            #line default
            #line hidden
, 434), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("<div");

WriteLiteral(" ng-controller=\"FormsAuthController\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n");

            
            #line 20 "..\..\Views\FormsAuth\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\FormsAuth\Index.cshtml"
     using (Html.BeginNgForm(x => x
        .OnSubmit("Login()")
        .CssClass("sg-form")
        ))
    {
        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\FormsAuth\Index.cshtml"
   Write(Html.NgEditorFor(x => x.Email, x => x
                .Input()
                .ModelPrefix("Model")
                .BootstrapFormControl()
                .BootstrapFormGroup()
                .LabelText(Html.Translate("Email"))
                .Attribute("type", "email")
                //.Attribute("ng-required", "true")
                //.Attribute("autocomplete", "off")
        ));

            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\FormsAuth\Index.cshtml"
         
        
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\FormsAuth\Index.cshtml"
   Write(Html.NgEditorFor(x => x.Password, x => x
                .Input()
                .BootstrapFormControl()
                .BootstrapFormGroup()
                .LabelText(Html.Translate("Password"))
                .Attribute("type", "password")
                //.Attribute("ng-required", "true")
        ));

            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\FormsAuth\Index.cshtml"
         
        
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\FormsAuth\Index.cshtml"
           
        
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\FormsAuth\Index.cshtml"
   Write(Html.NgEditorFor(x => x.RememberMe, x => x
                .UiCheckbox("left")
                .BootstrapFormControl()
                .BootstrapFormGroup()
                .LabelText(Html.Translate("Stay signed in?"))
        ));

            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\FormsAuth\Index.cshtml"
         
        
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\FormsAuth\Index.cshtml"
           
        using (Html.BeginBootstrapFormGroup())
        {
            
            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\FormsAuth\Index.cshtml"
       Write(Html.BootstrapButton(x => x
                .BootstrapButton("primary")
                .BeforeGlyph("ok")
                .LabelText(Html.Translate("Submit"))
                .Attribute("type", "submit")
                .Attribute("ng-disabled", "!FormIsValid()")
                .CssClass("margin-right-half")
            ));

            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\FormsAuth\Index.cshtml"
             

            
            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\FormsAuth\Index.cshtml"
       Write(Html.BootstrapButton(x => x
                .BootstrapButton("danger")
                .AfterGlyph("remove")
                .LabelText(Html.Translate("Reset"))
                .Attribute("type", "reset")
                .Attribute("ng-click", Html.PropertyExpression("Model.{0} = true;", y=> y.RememberMe))
            ));

            
            #line default
            #line hidden
            
            #line 83 "..\..\Views\FormsAuth\Index.cshtml"
             
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
