#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.FormsAuth
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\FormsAuth\NgView-Login-Forgot.cshtml"
    using Singular.Modules.Core.HtmlExtensions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\FormsAuth\NgView-Login-Forgot.cshtml"
    using Singular.Web.Mvc.Common.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/FormsAuth/NgView-Login-Forgot.cshtml")]
    public partial class NgView_Login_Forgot : System.Web.Mvc.WebViewPage<dynamic>
    {
        public NgView_Login_Forgot()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\FormsAuth\NgView-Login-Forgot.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Views\FormsAuth\NgView-Login-Forgot.cshtml"
 using (Html.BeginNgForm(x => x
        .OnSubmit("RetrievePassword()")
        .CssClass("sg-form")
        ))
{

            
            #line default
            #line hidden
WriteLiteral("    <h3>Forgot your password?</h3>    \r\n");

            
            #line 14 "..\..\Views\FormsAuth\NgView-Login-Forgot.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<hr />\r\n<p><a");

WriteLiteral(" alt-href=\"Login\"");

WriteLiteral(">");

            
            #line 17 "..\..\Views\FormsAuth\NgView-Login-Forgot.cshtml"
                  Write(Html.Translate("Back to login"));

            
            #line default
            #line hidden
WriteLiteral("</a></p>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
