#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Modules.Core.Views.FormsAuth
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
    using Singular.Modules.Core.HtmlExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/FormsAuth/NgView-Login-Index.cshtml")]
    public partial class NgView_Login_Index : System.Web.Mvc.WebViewPage<Singular.Modules.Core.Data.Models.FormsAuthModel>
    {
        public NgView_Login_Index()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>");

            
            #line 6 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
Write(Html.Translate("Login"));

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

            
            #line 8 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
 using (Html.BeginNgForm(x => x
    .OnSubmit("Login()")
    .CssClass("sg-form")
    ))
{
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
Write(Html.NgEditorFor(x => x.Email, x => x
        .Input()
        .Required()
        .ModelPrefix("Model")
        .BootstrapFormControl()
        .BootstrapFormGroup()
        .LabelText(Html.Translate("Email"))
        .Attribute("type", "email")
        //.Attribute("ng-required", "true")
        //.Attribute("autocomplete", "off")
        ));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
         
    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
Write(Html.NgEditorFor(x => x.Password, x => x
        .Input()
        .Required()
        .BootstrapFormControl()
        .BootstrapFormGroup()
        .LabelText(Html.Translate("Password"))
        .Attribute("type", "password")
        //.Attribute("ng-required", "true")
        ));

            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
         
    
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
           
    
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
Write(Html.NgEditorFor(x => x.RememberMe, x => x
        .UiCheckbox("left")
        .BootstrapFormControl()
        .BootstrapFormGroup()
        .LabelText(Html.Translate("Stay signed in?"))
        ));

            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
         
    
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
           
    using (Html.BeginBootstrapFormGroup())
    {
        
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
   Write(Html.BootstrapButton(x => x
            .BootstrapButton("primary")
            .BeforeGlyph("ok")
            .LabelText(Html.Translate("Submit"))
            .Attribute("type", "submit")
            //.Attribute("ng-disabled", "!FormIsValid()")
            .CssClass("margin-right-half")
            ));

            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
             

        
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
   Write(Html.BootstrapButton(x => x
            .BootstrapButton("danger")
            .AfterGlyph("remove")
            .LabelText(Html.Translate("Reset"))
            .Attribute("type", "reset")
            .Attribute("ng-click", Html.PropertyExpression("Model.{0} = true;", y => y.RememberMe))
            ));

            
            #line default
            #line hidden
            
            #line 73 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
             
    }
    
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
Write(Html.SgValidationErrors(null));

            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
                                  


            
            #line default
            #line hidden
WriteLiteral("    <hr />\r\n");

WriteLiteral("    <p><a");

WriteLiteral(" alt-href=\"Login,Forgot\"");

WriteLiteral(">");

            
            #line 78 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
                             Write(Html.Translate("Click here if you have forgotten your password"));

            
            #line default
            #line hidden
WriteLiteral("</a></p>\r\n");

            
            #line 79 "..\..\Views\FormsAuth\NgView-Login-Index.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
